services:
  db2:
    image: ibmcom/db2:latest
    container_name: ibmdb2luw
    restart: always
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=1StrongPsswd
      - DBNAME=pdt
      - ARCHIVE_LOGS=false
    ports:
      - "50000:50000"
    volumes:
      - db2_test_data:/database
    healthcheck:
      test: ["CMD-SHELL", "su - db2inst1 -c 'db2 connect to pdt user db2inst1 using 1StrongPsswd' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 80s

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-migrations
    depends_on:
      db2:
        condition: service_healthy
    command: -url=jdbc:db2://db2:50000/pdt -user=db2inst1 -password=1StrongPsswd -schemas=FLYWAY migrate
    volumes:
      - ./V1__init.sql:/flyway/sql/V1__init.sql
      - ./drivers/jcc-12.1.2.0.jar:/flyway/drivers/jcc-12.1.2.0.jar #use the latest version and change the file name

volumes:
  db2_test_data:
